config/routes.rb
Softcell::Application.routes.draw do
  resource  :dashboard, only:   [:show]
  resources :clients, except: [:index, :show]
  resources :invoices,  except: [:index] do
    member { get :print }
    member { post :clone }
  end

  root to: 'dashboards#show'
end

app/models/client.rb
class Client < ActiveRecord::Base
  STATES = [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District Of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]

  has_many :invoices

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true

  scope :alphabetical, -> { order(name: :asc) }
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  NET_PERIODS = [7, 15, 30, 60]
  BASE_INVOICE_NUMBER = 100

  belongs_to :client
  has_many :items

  validates :number, presence: true
  validates :title, presence: true
  validates :client_id, presence: true
  validates :net_id, presence: true

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: lambda { |item| item[:name].blank? }

  scope :descending,  -> { order('number DESC') }
  scope :outstanding, -> { where(paid_at: nil) }
  scope :total,       -> { scoped.pluck(:total).sum }

  # Class Methods

  def self.next_number
    self.last.nil? ? BASE_INVOICE_NUMBER : self.maximum(:number).succ
  end

  # Instance Methods

  def clone
    self.dup.tap do |cloned|
      cloned.items = self.items.map(&:dup)
      cloned.number = self.class.next_number
    end
  end

  def build_items(number: 1)
    number.times { items.build }

    self
  end

  def net
    NET_PERIODS[net_id.to_i]
  end

  def net=(value)
    self.net_id = NET_PERIODS.index(value.to_i)
  end

  def total
    items.map(&:cost).reduce(0, :+)
  end

  def due_at
    created_at.advance(days: self.net) if created_at.present?
  end

  def due?
    if due_at.present?
      due_at < Time.now
    else
      false
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :invoice

  validates :name, presence: true
  validates :cost, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.create(client_params)

    redirect_to dashboard_url
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)

    redirect_to dashboard_url
  end

  private

  def client_params
    params.require(:client).permit!
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @invoices = Invoice.descending.preload(:items)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def new
    @invoice = Invoice.new.build_items
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def edit
    @invoice = Invoice.find(params[:id]).build_items
  end

  def create
    @invoice = Invoice.create(invoice_params)

    redirect_to dashboard_path, notice: 'Invoice created'
  end

  def update
    @invoice = Invoice.find(params[:id])

    @invoice.update(invoice_params)

    redirect_to dashboard_path, notice: 'Invoice updated'
  end

  def print
    @invoice = Invoice.find(params[:id])

    render :print, layout: 'print'
  end

  def clone
    @invoice = Invoice.find(params[:id]).clone

    render :new
  end

  private

  def invoice_params
    params.require(:invoice).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def format_date(datetime)
    datetime.strftime("%b %d, %Y")
  end

  def format_currency(value)
    number_to_currency(value, precision: 2)
  end

  def invoice_class(invoice)
    return 'paid' if invoice.paid_at.present?
    return 'due'  if invoice.due?
    nil
  end

  def invoice_number(invoice)
    if invoice.new_record?
      invoice.class.next_number
    else
      invoice.number
    end
  end
end

app/views/clients/_form.html.haml
= simple_form_for @client do |form|
  %legend= @client.new_record? ? 'Add A New Client' : 'Edit Client'

  %fieldset
    = form.input :name
    = form.input :attention

  %fieldset
    = form.input :address
    = form.input :city
    = form.input :state, collection: Client::STATES, prompt: 'Select a State'
    = form.input :zipcode

  = form.button :submit

app/views/clients/edit.html.haml
= render partial: 'form'

app/views/clients/new.html.haml
= simple_form_for @client do |form|
  %legend Add A New Client

  %fieldset
    = form.input :name
    = form.input :attention

  %fieldset
    = form.input :address
    = form.input :city
    = form.input :state, collection: Client::STATES, prompt: 'Select a State'
    = form.input :zipcode

  = form.button :submit, 'Add Client'

app/views/dashboards/show.html.haml
%section.invoices= render 'invoices/listing'

app/views/invoices/_form.html.haml
= simple_form_for @invoice do |form|
  %legend= @invoice.new_record? ? 'Create A New Invoice' : 'Edit Invoice'

  = form.input :title
  = form.input :description, input_html: { rows: 4 }

  %fieldset
    = form.input :number, input_html: { value: invoice_number(@invoice) }
    = form.input :client_id, collection: Client.all, prompt: 'Choose a Client'
    = form.input :net, collection: Invoice::NET_PERIODS
    = form.input :created_at,
      order: [:day, :month, :year], discard_hour: true, discard_minute: true

  %fieldset#line-items
    %h2 Line Items
    = form.simple_fields_for :items do |item_form|
      .line-item
        = item_form.input :name, label: false, wrapper: false, required: false, input_html: { class: 'item-name' }
        = item_form.input :cost, label: false, wrapper: false, required: false, input_html: { class: 'item-cost' }

    %div.total
      %label Total
      %input{ id: 'line-item-total', type: 'text', disabled: 'disabled', value: '$0.00' }

  = form.button :submit

app/views/invoices/_invoice.html.haml
#badging.badging
  %h2 søren
  %p 414 S Gables Blvd <br />Wheaton IL 60187

#content.content
  %h2.title= invoice.title

  %table#meta.meta
    %tr
      %td.thead Client
      %td= invoice.client.name
    %tr
      %td.thead Attn
      %td= invoice.client.attention
      %tr
        %td.thead Address
        %td #{invoice.client.address} <br /> #{invoice.client.city} #{invoice.client.state}, #{invoice.client.zipcode}

  .description
    %p= invoice.description

#support.support
  %dl
    %dt Date
    %dd= format_date(invoice.created_at)
  %dl
    %dt Due
    %dd= format_date(invoice.due_at)
  %dl
    %dt Invoice Number
    %dd= sprintf('%05d', invoice.number)


%table#itemized.itemized
  %tr
    %th.item-head Item
    %th.cost-head Cost
  - invoice.items.each do |item|
    %tr
      %td.item= item.name
      %td.cost= format_currency(item.cost)
  %tr
    %td.total-head Total
    %td.total= format_currency(invoice.total)

app/views/invoices/_listing.html.haml
%table.invoices-table
  %thead
    %tr.header-row
      %th.number number
      %th.created created
      %th.due due
      %th.client client
      %th.title title
      %th.total total
  %tbody
    - @invoices.each do |invoice|
      %tr{ class: invoice_class(invoice) }
        %td.number= link_to invoice.number, invoice_path(invoice)
        %td.created= format_date(invoice.created_at)
        %td.due= format_date(invoice.due_at)
        %td.client= invoice.client.name
        %td.title= invoice.title
        %td.total= format_currency(invoice.total)
    %tr.footer
      %td.outstanding{ colspan: 5 } Outstanding
      %td.total= format_currency(Invoice.outstanding.map(&:total).sum)

app/views/invoices/index.html.haml
%h1 Invoices
= render 'invoices/listing'
= link_to 'Create New Invoice', new_invoice_path, class: 'large-button'

app/views/invoices/new.html.haml
= simple_form_for @invoice do |form|
  %legend Create A New Invoice

  %fieldset
    = form.input :title
    = form.input :description, input_html: { rows: 4 }

  %fieldset
    = form.input :number, input_html: { value: Invoice.next_number }
    = form.input :client_id, collection: Client.all, prompt: 'Choose a Client'
    = form.input :net_id, collection: Invoice::NET_PERIODS
    = form.input :created_at,
      order: [:day, :month, :year], discard_hour: true, discard_minute: true

  %fieldset#line-items
    %h2 Line Items
    = simple_fields_for :items do |item_form|
      = item_form.input :name, label: false, wrapper: false, input_html: { class: 'item-name' }
      = item_form.input :cost, label: false, wrapper: false, input_html: { value: '0.00', class: 'item-cost' }

    %div.total
      %label Total
      %input{ id: 'line-item-total', type: 'text', disabled: 'disabled', value: '$0.00' }

  = form.button :submit

app/views/invoices/print.html.haml
= render partial: @invoice

app/views/invoices/show.html.haml
%nav#invoice-toolbar.toolbar
  = link_to 'Print', print_invoice_path(@invoice), class: 'print'
  = link_to 'Edit', edit_invoice_path(@invoice), class: 'edit'
  = button_to 'Clone', clone_invoice_path(@invoice), class: 'clone'

= render partial: @invoice

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Softcell
    = stylesheet_link_tag :application
    = csrf_meta_tag

  %body{ id: controller.controller_name, class: controller.action_name }
    %header
      %nav
        = link_to 'Softcell', dashboard_url
        = link_to 'Create New Invoice', new_invoice_path, class: 'tool-button'
        = link_to 'Add a Client', new_client_path, class: 'tool-button'

    .container
      = yield

    = javascript_include_tag :application

app/views/layouts/print.html.haml
!!!5
%html
  %head
    %title #{@invoice.number} &mdash; #{@invoice.title}
    = stylesheet_link_tag 'print', media: 'all'
    = csrf_meta_tag

  %body{ id: controller.controller_name, class: controller.action_name }
    #container
      = yield